apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::783764571332:role/AmazonEKSHybridNodesRole
      username: system:node:{{SessionName}}
      groups:
        - system:bootstrappers
        - system:nodes
